### ISSUE TITLE
Discrepancies in PR 3286

### ISSUE THREAD

**Issue by akavel** [enso-org/enso#3304]
After the first round of QA/Acceptance Review testing on PR #3286 (https://www.pivotaltracker.com/story/show/180916527), focusing on the `library/getPackage` message, I found some discrepancies between what is described in the design doc, what happens actually, and what is described in the API docs. They fall mostly in two general categories:

 1. The yaml example from Design Doc does not work verbatim; various tweaks seem needed, and I'm not sure why and whether they are documented anywhere;
 2. The format of the response from `library/getPackage` seems to not match the format described in the API doc, both in field names and in field types (at various levels of nesting). 

A list of example cases I observed comes below.

### ***API documentation of `ComponentGroups.newGroups` field name is inconsistent with `.new` field being apparently returned instead***
```
{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"new":[{"module":"Gruuup 1","exports":["foo"]}]},"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":["foo"]}]}}}}
```

### ***Yaml semantics different than in Design Doc***
Snippet similar as presented in Design Doc does not work:
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
        exports:
          - foo

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":null,"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":{"exports":["foo"]}}]}}}}
```
Instead, snippet with different indentation (which conveys different semantics in YAML, as can be seen comparing the `"raw"` field in the response below vs. above) works:
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      exports:
        - foo

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"new":[{"module":"Gruuup 1","exports":["foo"]}]},"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":["foo"]}]}}}}
```
Similarly, adding a `shortcut` as in design doc does not work:
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      exports:
        - foo:
            shortcut: f

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":null,"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":[{"foo":{"shortcut":"f"}}]}]}}}}
```
but instead semantically different YAML document seems to work:
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      exports:
        - foo:
          shortcut: f

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"new":[{"module":"Gruuup 1","exports":[{"name":"foo","shortcut":"f"}]}]},"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":[{"foo":null,"shortcut":"f"}]}]}}}}
```

### ***Nonconforming response returned***
In response, at path `result.componentGroups.new[0].exports[0]` note a string value `"foo"`, where expected a `Component` containing `{"name":"foo"}`.
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      exports:
        - foo

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"new":[{"module":"Gruuup 1","exports":["foo"]}]},"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":["foo"]}]}}}}
```
In response, at path `result.componentGroups.new[0].exports[1]` note a string value `"bar"`, where expected a `Component` containing `{"name":"bar"}`.
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      exports:
        - foo:
          shortcut: f
        - bar

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"new":[{"module":"Gruuup 1","exports":[{"name":"foo","shortcut":"f"},"bar"]}]},"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"exports":[{"foo":null,"shortcut":"f"},"bar"]}]}}}}
```

### ***Empty response returned with no error message, even though component groups at least partially correct***
Is it described somewhere how we want to behave in case of partially correct input? Do we want to somehow provide error message to user to guide them what they did wrong? Notably, the `extends:` section in the document below was copied from the design doc.
```
name: Footest
component-groups:
  new:
    - Gruuup 1:
      color: '#aabbcc'
      icon: some-icon
      exports:
        - foo:
          shortcut: f
        - bar
    - Le gruppe 2:
      exports:
        - foo
  extends:
    - Base.Group 2:
      exports:
        - foo

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":null,"raw":{"name":"Footest","component-groups":{"new":[{"Gruuup 1":null,"color":"#aabbcc","icon":"some-icon","exports":[{"foo":null,"shortcut":"f"},"bar"]},{"Le gruppe 2":null,"exports":["foo"]}],"extends":[{"Base.Group 2":null,"exports":["foo"]}]}}}}
```

### ***API docs for `extendedGroups` field don't match actual semantics***
see https://github.com/enso-org/enso/blob/abbb3a467915eabf37e91329317ba6c3274fc1e0/docs/language-server/protocol-language-server.md#componentgroups
In example below:
 1. Instead of `.extendedGroup`, field named `extends` is returned
 2. At `result.componentGroups.extends[0].module`, expected a `ModuleReference` object according to API docs, but got a string `"Standard.Base.Main"` instead
```
name: Footest
component-groups:
  extends:
    - Standard.Base.Main:
      exports:
      - name: foo

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{"extends":[{"module":"Standard.Base.Main","exports":["foo"]}]},"raw":{"name":"Footest","component-groups":{"extends":[{"Standard.Base.Main":null,"exports":[{"name":"foo"}]}]}}}}
```
 

### ***Error code should be 8007, is 1000, for LocalLibraryNotFound***
Per definition of [LocalLibraryNotFound](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#locallibrarynotfound) message, referenced in the [errors section of `library/getPackage` message](https://github.com/enso-org/enso/blob/abbb3a467915eabf37e91329317ba6c3274fc1e0/docs/language-server/protocol-language-server.md#errors-74). Got code 1000 in transcript below:
```
{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Fooblah","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"error":{"code":1000,"message":"Local library [local.Fooblah] has not been found."}}
```

### ***Returned `componentGroups` field's empty value is sometimes `{}`, sometimes `null`***
Not strictly error, but possibly surprising behavior.
```
{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{},"raw":{"name":"Footest"}}}

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{},"raw":{"name":"Footest","component-groups":null}}}

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":{},"raw":{"name":"Footest","component-groups":{"new":null}}}}

{"jsonrpc":"2.0","id":5,"method":"library/getPackage","params":{"namespace":"local","name":"Footest","version":{"type":"LocalLibraryVersion"}}}
{"jsonrpc":"2.0","id":5,"result":{"license":null,"componentGroups":null,"raw":{"name":"Footest","component-groups":{"new":["Gruuup 1"]}}}}
```
